name: Java CI with Gradle

on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Make Gradlew executable
        run: |
          for entry in "${PWD}"/*
          do
            if [ -d "$entry" ]; then
              chmod +x "$entry"/gradlew
            fi
          done
        working-directory: Term2
      - name: Test with Gradle
        run: |
          for entry in "${PWD}"/*
          do
            if [ -d "$entry" ]; then
              cd "$entry"
              ./gradlew test
            fi
          done
        working-directory: Term2
